### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by ThomasLeigh**
Besides this little fix I can't find "language" label (used in app's settings to change the UI language).

### CODE REVIEW

**Comment by SIRSteiner** [comment]
Yes, I also have seen that but I think it should be in english. If anyone has set an unknown language he should be able to find this setting. That is always possible with the string 'language'

**Comment by ThomasLeigh** [comment]
Good point.

Another thing I've noticed: I can't find a "Turn on" string neither in Polish, nor English .xml file (it refers to the global filter editing screen).

**Comment by yanus171** [comment]
I have pulled new English strings with turnOn key

**Comment by yanus171** [comment]
Switch to master branch
С уважением, Алексей

Thomas Leigh <notifications@github.com> 26 декабря 2018 г. 17:28:50 написал:

**Comment by ThomasLeigh** [comment]
Can't find it there also:
https://github.com/yanus171/Flym/blob/master/FlymFork/src/main/res/values/strings.xml

**Comment by yanus171** [comment]
Search for turnOn key

**Pull request merged**
